name: github action needs

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello

  world:
    needs: hello
    runs-on: ubuntu-latest
    steps:
      - run: echo World
