name: github if test

on: push

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo Hello

  world:
    if: ${{ success() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo World
